- project:
    name: openstack-infra/afsmon
    templates:
      - system-required
      - openstack-python35-jobs
      - publish-to-pypi
    check:
      jobs:
        - openstack-tox-pep8
    gate:
      jobs:
        - openstack-tox-pep8